### PR TITLE
Added support for Nano S Plus

### PR DESCRIPTION
**Pull request by gjermundgaraba**
I recently got the new Ledger Nano S Plus, but it doesn't work for CLI clients made by the Cosmos SDK. I tracked the problem here and tested this on the Regen chain with great success.

If there is another route preferred to add support for this (for instance by updating this repo to match upstream and making the change there), let me know (although that would also require changes in ledger-cosmos-go).

### CODE REVIEW

**Comment by Chiccamandragora** [comment]
Hi, I can't use nano s plus with wasabi wallet, but I'd like to use it.
Do you know if there is a way to do it?

**Comment by philipglazman** [comment]
Tested locally on the new Ledger device and works as expected. Would be great to get this merged to fix upstream dependents.

**Review by jleni — APPROVED** [review]

**Comment by okwme** [comment]
great to see this merged!
will there be a new release @jleni or should we just target the commit in main?

**Comment by okwme** [comment]
hello @jleni just following up here

**Comment by ftheirs** [comment]
Hi @okwme, I apologize for the delay! The release was created! 🎉

**Comment by okwme** [comment]
thank you @ftheirs !

**Pull request merged**
