### PR TITLE
Remove suprious OSX USB Reads

### PR DESCRIPTION
**Pull request by chillyvee**
Transaction approval with Ledger + OS X often fails due to:
1) Packets full of zeros being read
2) Packets out of sequence being read

This patch filters all zero filled packets and ensures each USB exchange (Send + Receive) start on proper sequence boundaries.

### CODE REVIEW

**Comment by chillyvee** [comment]
Example usage: https://pastebin.com/bRSedjxn

**Comment by chillyvee** [comment]
Feedback is positive:
https://twitter.com/KevinGarrison/status/1588151637432012800

**Comment by chillyvee** [comment]
Additional positive tester feedback:
https://twitter.com/rhinostake/status/1588161469623013377

**Comment by Galadrin** [comment]
I have never had this problem under Linux.
I've only had a few opportunities to use the CLI during the last weeks.
- - -
Cros Nest

**Comment by chillyvee** [comment]
> I have never had this problem under Linux. I've only had a few opportunities to use the CLI during the last weeks.
> 
> Cros Nest

Suspect it might be an OSX specific "bug", but this code shouldn't break other OSes "in theory".

**Comment by jleni** [comment]
closing as this has been merged upstream

**Pull request closed without merging**
